Import libraries

In [ ]:
import pandas as pd
from datasets import load_dataset

Load Dataset

In [ ]:
dataset = load_dataset("Tobi-Bueck/customer-support-tickets")
df = dataset['train'].to_pandas()

print("Shape:", df.shape)
df.head()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

aa_dataset-tickets-multi-lang-5-2-50-ver(…):   0%|          | 0.00/26.0M [00:00<?, ?B/s]

(…)set-tickets-german_normalized_50_5_2.csv: 0.00B [00:00, ?B/s]

dataset-tickets-multi-lang-4-20k.csv:   0%|          | 0.00/18.8M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/61765 [00:00<?, ? examples/s]

Shape: (61765, 16)

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51.0,Security,Outage,Disruption,Data Breach,None,None,None,None
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51.0,Account,Disruption,Outage,IT,Tech Support,None,None,None
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51.0,Product,Feature,Tech Support,None,None,None,None,None
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51.0,Billing,Payment,Account,Documentation,Feedback,None,None,None
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en,51.0,Product,Feature,Feedback,Tech Support,None,None,None,None

In [ ]:
print(df.columns)
df.info()

Index(['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language',
       'version', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6',
       'tag_7', 'tag_8'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61765 entries, 0 to 61764
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   56466 non-null  object
 1   body      61763 non-null  object
 2   answer    48576 non-null  object
 3   type      48587 non-null  object
 4   queue     61765 non-null  object
 5   priority  61765 non-null  object
 6   language  61765 non-null  object
 7   version   28587 non-null  float64
 8   tag_1     48587 non-null  object
 9   tag_2     48528 non-null  object
 10  tag_3     48356 non-null  object
 11  tag_4     43990 non-null  object
 12  tag_5     27636 non-null  object
 13  tag_6     13225 non-null  object
 14  tag_7     5968 non-null   object
 15  tag_8     2472 non-null   object
dtypes: float64(1), object(15)
memory usage: 7.5+ MB

In [ ]:
print(df.isnull().sum())

subject      5299
body            2
answer      13189
type        13178
queue           0
priority        0
language        0
version     33178
tag_1       13178
tag_2       13237
tag_3       13409
tag_4       17775
tag_5       34129
tag_6       48540
tag_7       55797
tag_8       59293
dtype: int64

In [ ]:
# Combine subject + body safely
df['text'] = (df['subject'].fillna('') + " " + df['body'].fillna('')).str.strip()

# Remove empty text
df = df[df['text'] != ""].copy()

# Remove duplicates (important)
df = df.drop_duplicates(subset=['text', 'queue'])

print("Final shape:", df.shape)

Final shape: (53459, 17)

In [ ]:
df = df[df['text'].str.len() > 10]

In [ ]:
df = df.drop_duplicates(subset=['text', 'queue'])
print("After removing duplicates:", df.shape)

After removing duplicates: (53458, 17)

In [ ]:
labels = sorted(df['queue'].unique().tolist())

label2id = {label: i for i, label in enumerate(labels)}
id2label = {i: label for label, i in label2id.items()}

df['label'] = df['queue'].map(label2id)

print(label2id)

{'Arts & Entertainment/Movies': 0, 'Arts & Entertainment/Music': 1, 'Autos & Vehicles/Maintenance': 2, 'Autos & Vehicles/Sales': 3, 'Beauty & Fitness/Cosmetics': 4, 'Beauty & Fitness/Fitness Training': 5, 'Billing and Payments': 6, 'Books & Literature/Fiction': 7, 'Books & Literature/Non-Fiction': 8, 'Business & Industrial/Manufacturing': 9, 'Customer Service': 10, 'Finance/Investments': 11, 'Finance/Personal Finance': 12, 'Food & Drink/Groceries': 13, 'Food & Drink/Restaurants': 14, 'Games': 15, 'General Inquiry': 16, 'Health/Medical Services': 17, 'Health/Mental Health': 18, 'Hobbies & Leisure/Collectibles': 19, 'Hobbies & Leisure/Crafts': 20, 'Home & Garden/Home Improvement': 21, 'Home & Garden/Landscaping': 22, 'Human Resources': 23, 'IT & Technology/Hardware Support': 24, 'IT & Technology/Network Infrastructure': 25, 'IT & Technology/Security Operations': 26, 'IT & Technology/Software Development': 27, 'IT Support': 28, 'Jobs & Education/Online Courses': 29, 'Jobs & Education/Recruitment': 30, 'Law & Government/Government Services': 31, 'Law & Government/Legal Advice': 32, 'News': 33, 'Online Communities/Forums': 34, 'Online Communities/Social Networks': 35, 'People & Society/Culture & Society': 36, 'Pets & Animals/Pet Services': 37, 'Pets & Animals/Veterinary Care': 38, 'Product Support': 39, 'Real Estate': 40, 'Returns and Exchanges': 41, 'Sales and Pre-Sales': 42, 'Science/Environmental Science': 43, 'Science/Research': 44, 'Service Outages and Maintenance': 45, 'Shopping/E-commerce': 46, 'Shopping/Retail Stores': 47, 'Sports': 48, 'Technical Support': 49, 'Travel & Transportation/Air Travel': 50, 'Travel & Transportation/Land Travel': 51}

In [ ]:
#train test split
from sklearn.model_selection import train_test_split

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['text'],
    df['label'],
    test_size=0.2,
    stratify=df['label'],
    random_state=42
)

train_df = pd.DataFrame({'text': train_texts, 'label': train_labels})
val_df = pd.DataFrame({'text': val_texts, 'label': val_labels})

print(train_df.shape, val_df.shape)

(42766, 2) (10692, 2)

In [ ]:
#Model
from transformers import AutoTokenizer

model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
def tokenize(example):
    return tokenizer(
        example['text'],
        truncation=True,
        padding='max_length',
        max_length=256
    )

In [ ]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)

train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
val_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

Map:   0%|          | 0/42766 [00:00<?, ? examples/s]

Map:   0%|          | 0/10692 [00:00<?, ? examples/s]

In [ ]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(labels),
    id2label=id2label,
    label2id=label2id
)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Metrics

In [ ]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import numpy as np

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

Training Arguments

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01
)

In [ ]:
# Trainer
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=8019, training_loss=1.650479144386437, metrics={'train_runtime': 6531.8901, 'train_samples_per_second': 19.642, 'train_steps_per_second': 1.228, 'total_flos': 1.688588826753024e+16, 'train_loss': 1.650479144386437, 'epoch': 3.0})

In [ ]:
results = trainer.evaluate()
print(results)

{'eval_loss': 1.2814157009124756, 'eval_accuracy': 0.5679947624392069, 'eval_f1': 0.5499170720960358, 'eval_precision': 0.5696517938503634, 'eval_recall': 0.5679947624392069, 'eval_runtime': 167.5687, 'eval_samples_per_second': 63.807, 'eval_steps_per_second': 3.992, 'epoch': 3.0}

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Prediction Function

In [ ]:
def predict(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    )


    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    outputs = model(**inputs)
    probs = outputs.logits.softmax(dim=1)
    pred = probs.argmax().item()

    return id2label[pred]

Test

In [ ]:
print(predict("Payment failed twice"))

Billing and Payments

In [ ]:
print(predict("Cannot login account"))

Technical Support

In [ ]:
print(predict("Product damaged during delivery"))

Returns and Exchanges